version: "3"
services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks: 
      - poll-tier
    environment:
      - "REDIS_HOSTNAME=redis"
    restart: on-failure
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    environment:
      - POLL_HOSTNAME=poll
      - WORKER_HOSTNAME=worker
    restart: on-failure
  worker:
    build: ./worker
    restart: on-failure
    networks:
      - back-tier
    environment:
      - DB_HOSTNAME=db
      - REDIS_HOSTNAME=redis
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - result-tier
      - back-tier
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
  result:
    build: ./result
    ports: 
      - "5001:80"
    networks:
      - result-tier
    environment:
      - DB_HOSTNAME=db
    restart: on-failure

networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data:

