##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## epitech > epita
##
NAME	= 101pong

all: $(NAME)

$(NAME):
			cp main.py 101pong
			chmod +x 101pong

clean:

fclean:
	rm -rf 101pong

re:			fclean all

.PHONY:		all clean fclean re
