CREATE DATABASE IF NOT EXISTS epytodo;

CREATE TABLE IF NOT EXISTS epytodo.user (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(45) UNIQUE NOT NULL,
  password VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  firstname VARCHAR(45) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS epytodo.todo (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NOT NULL,
  description VARCHAR(45) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  due_time DATETIME NOT NULL,
  status VARCHAR(45) NOT NULL,
  user_id INT UNSIGNED,
  FOREIGN KEY (user_id) REFERENCES epytodo.user (id) 
);
